### ISSUE TITLE
Need two HTTP requests

### ISSUE THREAD

**Issue by mtjoernelund** [jishi/sonos-event-stub#1]
Hi Jishi, 

This stub works absolutely perfectly, save for one thing which I think is down to my lack of expertise in node. I am attempting to incorporate two sequentially issued http get requests in order to (i) turn on my amp and (ii) switch to the right input for my Sonos. 
I have the request() module and I can make it call the power on command, but I can for the love of me not figure out how to make it call the second http get call afterwards. I know that this is way out with the scope of this, but any pointers on this would be highly appreciated!

**Comment by jishi** [comment]
Sort of depends if you want to wait for the first to finish or not. The most obvious way is to just put them right after eachother, but then it will also send the requests more or less at the same time which might not work.

The second option is to invoke the second request, in the callback of the first request. That way, at least the request will finish. However, it might not guarantee that the AMP is ready for the next command. It sort of depends how it's internals work.

Example:

```
request({...options...}, function () {
    // This is the callback
    request({...options for 2nd request});
});
```
